In [1]:
# 필요한 라이브러리 불러오기
import pandas as pd

In [5]:
# 시군별 지체 + 뇌병변 장애인수 파일 불러오기
file_path = './원본데이터/장애유형별_장애인_성_시군구별__20220623122044.csv'
num_df = pd.read_csv(file_path, encoding='euc-kr', header=1)
num_df

       시군구별 장애유형별      전체
0     서울특별시    지체  185424
1     서울특별시   뇌병변   42287
2     부산광역시    지체   82660
3     부산광역시   뇌병변   20060
4     대구광역시    지체   54677
5     대구광역시   뇌병변   13094
6     인천광역시    지체   70758
7     인천광역시   뇌병변   13068
8     광주광역시    지체   31607
9     광주광역시   뇌병변    6875
10    대전광역시    지체   34269
11    대전광역시   뇌병변    7523
12    울산광역시    지체   24381
13    울산광역시   뇌병변    4881
14  세종특별자치시    지체    5296
15  세종특별자치시   뇌병변     935
16      경기도    지체  268832
17      경기도   뇌병변   53728
18      강원도    지체   51550
19      강원도   뇌병변    9316
20     충청북도    지체   46957
21     충청북도   뇌병변    8789
22     충청남도    지체   64668
23     충청남도   뇌병변   10965
24     전라북도    지체   67516
25     전라북도   뇌병변   12274
26     전라남도    지체   73318
27     전라남도   뇌병변   11682
28     경상북도    지체   83226
29     경상북도   뇌병변   16100
30     경상남도    지체   94245
31     경상남도   뇌병변   17714
32  제주특별자치도    지체   14746
33  제주특별자치도   뇌병변    3528

In [7]:
# 시군별로 그룹화하여 더하기
num_df_total = num_df.groupby('시군구별')[['전체']].sum()
num_df_total

             전체
시군구별
강원도       60866
경기도      322560
경상남도     111959
경상북도      99326
광주광역시     38482
대구광역시     67771
대전광역시     41792
부산광역시    102720
서울특별시    227711
세종특별자치시    6231
울산광역시     29262
인천광역시     83826
전라남도      85000
전라북도      79790
제주특별자치도   18274
충청남도      75633
충청북도      55746

In [10]:
# 충전기 파일 불러오기
file_path = './원본데이터/추가_전국전동휠체어급속충전기표준데이터.csv'
batt_df = pd.read_csv(file_path, encoding='euc-kr')
batt_df

,시설명,시도명,시군구명,시군구코드,소재지도로명주소,소재지지번주소,위도,경도,설치장소설명,평일운영시작시각,...,공휴일운영시작시각,공휴일운영종료시각,동시사용가능대수,공기주입가능여부,휴대전화충전가능여부,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명
0,용산행복장애인자립생활센터,서울특별시,용산구,11170,서울특별시 용산구 원효로89길 31,NaN,37.540745,126.967358,센터 1층,09:00,...,00:00,00:00,2,Y,Y,용산행복장애인자립생활센터,02-704-0420,2021-09-15,3020000,서울특별시 용산구
1,간석3동행정복지센터,인천광역시,남동구,28200,인천광역시 남동구 용천로 186 (간석동),인천광역시 남동구 간석동 49-1,37.466111,126.714686,행정복지센터,09:00,...,00:00,00:00,2,Y,Y,인천광역시 남동구,032-453-2572,2022-03-04,3530000,인천광역시 남동구
2,간석4동행정복지센터,인천광역시,남동구,28200,인천광역시 남동구 석정로 575 (간석동),인천광역시 남동구 간석동 612-1,37.467324,126.699152,행정복지센터,09:00,...,00:00,00:00,2,Y,Y,인천광역시 남동구,032-453-2572,2022-03-04,3530000,인천광역시 남동구
3,만수2동행정복지센터,인천광역시,남동구,28200,인천광역시 남동구 만수서로 46 (만수동),인천광역시 남동구 만수동 1116-2,37.461387,126.731157,행정복지센터,09:00,...,00:00,00:00,2,Y,Y,인천광역시 남동구,032-453-2572,2022-03-04,3530000,인천광역시 남동구
4,장수서창동행정복지센터,인천광역시,남동구,28200,인천광역시 남동구 독곡로 28 (장수서창동),인천광역시 남동구 서창동 558-2,37.435880,126.747361,행정복지센터,09:00,...,00:00,00:00,2,Y,Y,인천광역시 남동구,032-453-2572,2022-03-04,3530000,인천광역시 남동구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2939,겸재정선미술관,서울특별시,강서구,11500,서울특별시 강서구 양천로47길 36,서울특별시 강서구 가양동 243-1,37.572223,126.838412,2층,10:00,...,10:00,17:00,2,Y,Y,겸재정선미술관,02-2659-2206,2022-02-14,3150000,서울특별시 강서구
2940,등촌3동주민센터,서울특별시,강서구,11500,서울특별시 강서구 화곡로63길 96,서울특별시 강서구 등촌동 705-4,37.558888,126.847919,1층,09:00,...,00:00,00:00,2,Y,Y,서울특별시 강서구 등촌3동주민센터,02-2600-7445,2022-02-14,3150000,서울특별시 강서구
2941,가양4종합사회복지관,서울특별시,강서구,11500,서울특별시 강서구 양천로57길 37,서울특별시 강서구 가양동 1478 가양4단지아파트,37.565932,126.852069,1층,09:00,...,00:00,00:00,2,Y,Y,가양4종합사회복지관,02-2668-6689,2022-02-14,3150000,서울특별시 강서구
2942,가양5종합사회복지관,서울특별시,강서구,11500,서울특별시 강서구 양천로 57길 36,서울특별시 강서구 가양동 1481 가양5단지아파트,37.564627,126.853520,1층,09:00,...,00:00,00:00,2,Y,Y,가양5종합사회복지관,02-2668-4603,2022-02-14,3150000,서울특별시 강서구
2943,등촌4종합사회복지관,서울특별시,강서구,11500,서울특별시 강서구 공항대로39길 59,서울특별시 강서구 등촌동 690 등촌4단지주공아파트,37.562259,126.842895,1층,09:00,...,00:00,00:00,2,Y,Y,등촌4종합사회복지관,02-2658-8800,2022-02-14,3150000,서울특별시 강서구

In [15]:
# 시도명으로 그룹화하여 한번에 동시사용가능한 모든 대수 더하기
batt_df_total = batt_df.groupby('시도명')[['동시사용가능대수']].sum()
batt_df_total

         동시사용가능대수
시도명
강원도           348
경기도           827
경상남도          334
경상북도          358
광주광역시         193
대구광역시         191
대전광역시         165
부산광역시         267
서울특별시         933
세종특별자치시        14
울산광역시          96
인천광역시         274
전라남도          303
전라북도          344
제주특별자치도       312
충청남도          242
충청북도          102

In [28]:
# 전동휠체어를 보유한 사람과 사용가능대수를 나눠서
# 충전소 1대당 커버해야하는 인원수 계산하여 one_batt_에 저장
one_batt_ = round((num_df_total['전체']  * 0.067) / batt_df_total['동시사용가능대수'], 1)
one_batt_

시군구별
강원도        11.7
경기도        26.1
경상남도       22.5
경상북도       18.6
광주광역시      13.4
대구광역시      23.8
대전광역시      17.0
부산광역시      25.8
서울특별시      16.4
세종특별자치시    29.8
울산광역시      20.4
인천광역시      20.5
전라남도       18.8
전라북도       15.5
제주특별자치도     3.9
충청남도       20.9
충청북도       36.6
dtype: float64

In [29]:
# one_batt_.to_csv('C:/DEV/STUDY/miniproject/data/정제데이터/one_batt.csv')